#登录界面
import resoure
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.ApplicationModal)
        Login.resize(739, 401)
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(310, 20, 111, 41))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.user = QtWidgets.QLabel(Login)
        self.user.setGeometry(QtCore.QRect(140, 100, 91, 41))
        self.user.setObjectName("user")
        self.password = QtWidgets.QLabel(Login)
        self.password.setGeometry(QtCore.QRect(140, 160, 91, 26))
        self.password.setObjectName("password")
        self.identify = QtWidgets.QLabel(Login)
        self.identify.setGeometry(QtCore.QRect(140, 200, 91, 59))
        self.identify.setObjectName("identify")
        self.userline = QtWidgets.QLineEdit(Login)
        self.userline.setGeometry(QtCore.QRect(290, 110, 191, 21))
        self.userline.setObjectName("userline")
        self.pwline = QtWidgets.QLineEdit(Login)
        self.pwline.setGeometry(QtCore.QRect(290, 160, 191, 21))
        self.pwline.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwline.setObjectName("pwline")
        self.idbox = QtWidgets.QComboBox(Login)
        self.idbox.setGeometry(QtCore.QRect(320, 220, 121, 22))
        self.idbox.setObjectName("idbox")
        self.idbox.addItem("")
        self.idbox.addItem("")
        self.idbox.addItem("")
        self.loginbt = QtWidgets.QPushButton(Login)
        self.loginbt.setGeometry(QtCore.QRect(210, 310, 93, 28))
        self.loginbt.setObjectName("loginbt")
        self.exitbt = QtWidgets.QPushButton(Login)
        self.exitbt.setGeometry(QtCore.QRect(450, 310, 93, 28))
        self.exitbt.setObjectName("exitbt")

        self.listView = QtWidgets.QListView(Login)
        self.listView.setGeometry(QtCore.QRect(-840, -770, 1831, 1181))
        self.listView.setStyleSheet("background-image: url(:image/1.jpg);")
        self.listView.setObjectName("listView")
        self.listView.raise_()
        self.label.raise_()
        self.user.raise_()
        self.password.raise_()
        self.identify.raise_()
        self.userline.raise_()
        self.pwline.raise_()
        self.idbox.raise_()
        self.loginbt.raise_()
        self.exitbt.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "图书馆管理系统"))
        self.label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">用户登录</span></p></body></html>"))
        self.user.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">用户账号</span></p></body></html>"))
        self.password.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">用户密码</span></p></body></html>"))
        self.identify.setText(_translate("Login","<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">身份类型</span></p></body></html>"))
        self.idbox.setItemText(0, _translate("Login", "读者"))
        self.idbox.setItemText(1, _translate("Login", "图书管理员"))
        self.idbox.setItemText(2, _translate("Login", "系统管理员"))
        self.loginbt.setText(_translate("Login", "登录"))
        self.exitbt.setText(_translate("Login", "退出"))
